/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const EmergencyContact = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Text,
  'phone' : IDL.Text,
});
export const Guide = IDL.Record({
  'name' : IDL.Text,
  'languages' : IDL.Vec(IDL.Text),
  'description' : IDL.Text,
  'email' : IDL.Text,
  'specialty' : IDL.Text,
  'phone' : IDL.Text,
});
export const Place = IDL.Record({
  'region' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'googleMapsUrl' : IDL.Text,
  'imageKeyword' : IDL.Text,
});
export const Hotel = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Text,
  'website' : IDL.Text,
  'googleMapsUrl' : IDL.Text,
  'priceRange' : IDL.Text,
  'phone' : IDL.Text,
  'location' : IDL.Text,
});
export const TravelTipCategory = IDL.Variant({
  'Food' : IDL.Null,
  'Safety' : IDL.Null,
  'Etiquette' : IDL.Null,
  'Emergency' : IDL.Null,
});
export const TravelTip = IDL.Record({
  'title' : IDL.Text,
  'content' : IDL.Text,
  'category' : TravelTipCategory,
});

export const idlService = IDL.Service({
  'getEmergencyContacts' : IDL.Func([], [IDL.Vec(EmergencyContact)], ['query']),
  'getGuides' : IDL.Func([], [IDL.Vec(Guide)], ['query']),
  'getHiddenGems' : IDL.Func([], [IDL.Vec(Place)], ['query']),
  'getHotels' : IDL.Func([], [IDL.Vec(Hotel)], ['query']),
  'getPlaces' : IDL.Func([], [IDL.Vec(Place)], ['query']),
  'getTravelTips' : IDL.Func([], [IDL.Vec(TravelTip)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const EmergencyContact = IDL.Record({
    'name' : IDL.Text,
    'description' : IDL.Text,
    'phone' : IDL.Text,
  });
  const Guide = IDL.Record({
    'name' : IDL.Text,
    'languages' : IDL.Vec(IDL.Text),
    'description' : IDL.Text,
    'email' : IDL.Text,
    'specialty' : IDL.Text,
    'phone' : IDL.Text,
  });
  const Place = IDL.Record({
    'region' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'googleMapsUrl' : IDL.Text,
    'imageKeyword' : IDL.Text,
  });
  const Hotel = IDL.Record({
    'name' : IDL.Text,
    'description' : IDL.Text,
    'website' : IDL.Text,
    'googleMapsUrl' : IDL.Text,
    'priceRange' : IDL.Text,
    'phone' : IDL.Text,
    'location' : IDL.Text,
  });
  const TravelTipCategory = IDL.Variant({
    'Food' : IDL.Null,
    'Safety' : IDL.Null,
    'Etiquette' : IDL.Null,
    'Emergency' : IDL.Null,
  });
  const TravelTip = IDL.Record({
    'title' : IDL.Text,
    'content' : IDL.Text,
    'category' : TravelTipCategory,
  });
  
  return IDL.Service({
    'getEmergencyContacts' : IDL.Func(
        [],
        [IDL.Vec(EmergencyContact)],
        ['query'],
      ),
    'getGuides' : IDL.Func([], [IDL.Vec(Guide)], ['query']),
    'getHiddenGems' : IDL.Func([], [IDL.Vec(Place)], ['query']),
    'getHotels' : IDL.Func([], [IDL.Vec(Hotel)], ['query']),
    'getPlaces' : IDL.Func([], [IDL.Vec(Place)], ['query']),
    'getTravelTips' : IDL.Func([], [IDL.Vec(TravelTip)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };