/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface EmergencyContact {
  'name' : string,
  'description' : string,
  'phone' : string,
}
export interface Guide {
  'name' : string,
  'languages' : Array<string>,
  'description' : string,
  'email' : string,
  'specialty' : string,
  'phone' : string,
}
export interface Hotel {
  'name' : string,
  'description' : string,
  'website' : string,
  'googleMapsUrl' : string,
  'priceRange' : string,
  'phone' : string,
  'location' : string,
}
export interface Place {
  'region' : string,
  'name' : string,
  'description' : string,
  'googleMapsUrl' : string,
  'imageKeyword' : string,
}
export interface TravelTip {
  'title' : string,
  'content' : string,
  'category' : TravelTipCategory,
}
export type TravelTipCategory = { 'Food' : null } |
  { 'Safety' : null } |
  { 'Etiquette' : null } |
  { 'Emergency' : null };
export interface _SERVICE {
  'getEmergencyContacts' : ActorMethod<[], Array<EmergencyContact>>,
  'getGuides' : ActorMethod<[], Array<Guide>>,
  'getHiddenGems' : ActorMethod<[], Array<Place>>,
  'getHotels' : ActorMethod<[], Array<Hotel>>,
  'getPlaces' : ActorMethod<[], Array<Place>>,
  'getTravelTips' : ActorMethod<[], Array<TravelTip>>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];